[FIX]开启管理员身份验证后，mongo3（arbiter节点）自检会失败，baseproject/kad#45

diff --git a/roles/ruijie/mongo/templates/mongo-conf.yaml.j2 b/roles/ruijie/mongo/templates/mongo-conf.yaml.j2
--- a/roles/ruijie/mongo/templates/mongo-conf.yaml.j2
+++ b/roles/ruijie/mongo/templates/mongo-conf.yaml.j2
@@ -15,3 +15,15 @@ data:
       echo "[`date +%Y%m%d_%H:%M:%S`]>>>find mongo error: $result, restart it" >> $LOG_FILE
       exit 1
     fi
+
+  liveness-probe-sh-noauth: |-
+    #!/bin/bash
+    LOG_FILE=/data/db/mongo_liveness.log
+    result=`mongo --eval 'r1=rs.status(); r2=""; if(r1.ok==1 && r1.myState==6) r2="1,"+r1.myState; if(r1.ok==0 && r1.code!=94) r2="0,"+r1.code; r2;' --quiet`
+    if [ "$result"x == ""x ]
+    then
+      exit 0
+    else
+      echo "[`date +%Y%m%d_%H:%M:%S`]>>>find mongo error: $result, restart it" >> $LOG_FILE
+      exit 1
+    fi
